In [2]:
import pandas as pd
import numpy as np

In [3]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [4]:
movies = movies.merge(credits,on='title')

In [5]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [6]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [7]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [9]:
movies.dropna(inplace=True)

In [10]:
movies.duplicated().sum()

0

In [11]:
import ast

In [12]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [13]:
movies['genres'] = movies['genres'].apply(convert)

In [14]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [15]:
movies['keywords'] = movies['keywords'].apply(convert)

In [16]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [17]:
movies['cast'] = movies['cast'].apply(convert)

In [18]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [19]:
import ast

In [20]:
def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter+=1
        else:
            break;
    return L

In [21]:
movies['crew'] = movies['crew'].apply(convert3)

In [22]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[Stephen E. Rivkin, Rick Carter, Christopher B..."

In [23]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [24]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[Stephen E. Rivkin, Rick Carter, Christopher B..."

In [25]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

In [26]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[Stephen E. Rivkin, Rick Carter, Christopher B..."

In [27]:
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [28]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...","[StephenE.Rivkin, RickCarter, ChristopherBoyes]"

In [29]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['cast'] + movies['crew']

In [30]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...","[StephenE.Rivkin, RickCarter, ChristopherBoyes]","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...","[DariuszWolski, GoreVerbinski, JerryBruckheimer]","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...","[ThomasNewman, SamMendes, AnnaPinnock]","[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...","[HansZimmer, CharlesRoven, ChristopherNolan]","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...","[AndrewStanton, AndrewStanton, JohnLasseter]","[John, Carter, is, a, war-weary,, former, mili..."

In [31]:
new_df = movies[['movie_id','title','tags']]

In [32]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\susha\AppData\Local\Temp/ipykernel_6012/3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [33]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\susha\AppData\Local\Temp/ipykernel_6012/3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [35]:
cv.fit_transform(new_df['tags']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [36]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [37]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [38]:
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1930s',
 '1950s',
 '1960s',
 '1970s',
 '19th',
 '20',
 '200',
 '20th',
 '24',
 '25',
 '30',
 '40',
 '50',
 '60',
 '60s',
 'aaron',
 'aaroneckhart',
 'aarontaylor',
 'aaronyoo',
 'aasifmandvi',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abrahambenrubi',
 'abuse',
 'abusive',
 'academy',
 'accept',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'account',
 'accused',
 'ace',
 'achieve',
 'act',
 'action',
 'actions',
 'activities',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adambrody',
 'adamgoldberg',
 'adamlefevre',
 'adams',
 'adamsandler',
 'adamscott',
 'adaptation',
 'addiction',
 'adewaleakinnuoye',
 'adopted',
 'adrianmartinez',
 'adrianscarborough',
 'adrienbrody',
 'adult',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affections',
 'afghanistan',
 'africa',
 'african',
 'aftermath',
 'agbaje',
 'age',
 'aged',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aidanquinn',
 'aided',
 'ailing',
 'air',
 'airport',
 'aka',
 'al',
 'alanalda',
 'alanarkin',
 'alancumming',
 'alanrickman',
 'alansilvestri',
 'alantudyk',
 'alaska',
 'albert',
 'albertbrooks',
 'albertfinney',
 'albertr',
 'alcoholic',
 'alecbaldwin',
 'alecguinness',
 'alejandrogonzáleziñárritu',
 'alessandronivola',
 'alex',
 'alexandersiddig',
 'alexanderskarsgård',
 'alexandredesplat',
 'alexapenavega',
 'alexborstein',
 'alexisbledel',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'alfrewoodard',
 'ali',
 'alice',
 'alicedrummond',
 'aliciasilverstone',
 'aliciawitt',
 'alien',
 'aliens',
 'alike',
 'alilarter',
 'alive',
 'allancorduner',
 'allen',
 'allencovert',
 'alleong',
 'alliance',
 'allied',
 'allies',
 'allisonjanney',
 'allow',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alter',
 'alternate',
 'alternative',
 'alunarmstrong',
 'amanda',
 'amandamackey',
 'amandapeet',
 'amandaseyfried',
 'amazing',
 'amberheard',
 'ambervalletta',
 'ambition',
 'ambitious',
 'america',
 'americaferrera',
 'american',
 'americans',
 'amid',
 'amidst',
 'amp',
 'amy',
 'amyadams',
 'amypoehler',
 'amyryan',
 'amysedaris',
 'amysmart',
 'anagasteyer',
 'analyst',
 'ancient',
 'anderson',
 'andiemacdowell',
 'andreamartin',
 'andrebraugher',
 'andrew',
 'andrewdaly',
 'andrewstanton',
 'andy',
 'andydick',
 'andygarcía',
 'andyrichter',
 'andysamberg',
 'andyserkis',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angelo',
 'angry',
 'angusmacinnes',
 'animal',
 'animals',
 'animated',
 'animation',
 'anjelicahuston',
 'ann',
 'anna',
 'annafaris',
 'annakendrick',
 'annalevine',
 'annapaquin',
 'annapinnock',
 'annasophiarobb',
 'anndowd',
 'anne',
 'annebancroft',
 'annefletcher',
 'annehathaway',
 'anneheche',
 'annemccarthy',
 'annemoss',
 'annettebening',
 'annie',
 'annikapergament',
 'annual',
 'answer',
 'answers',
 'anthony',
 'anthonyanderson',
 'anthonybregman',
 'anthonyhopkins',
 'anthonymackie',
 'anti',
 'antics',
 'antonicorone',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartment',
 'apes',
 'apocalypse',
 'apocalyptic',
 'appear',
 'appears',
 'apple',
 'apprentice',
 'approaches',
 'april',
 'architect',
 'arcy',
 'area',
 'arielwinter',
 'arigraynor',
 'arise',
 'armed',
 'arminmueller',
 'arms',
 'armstrong',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arnonmilchan',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'arriving',
 'art',
 'arthur',
 'arthurj',
 'arthurtovey',
 'artist',
 'artists',
 'artlinson',
 'arts',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'aside',
 'ask',
 'asked',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassination',
 'assassins',
 'assigned',
 'assignment',
 'assistant',
 'assumes',
 'astronaut',
 'astronauts',
 'asylum',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attending',
 'attention',
 'attitude',
 'attorney',
 'attractive',
 'august',
 'aunjanueellis',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'avaacres',
 'avenge',
 'average',
 'avoid',
 'avykaufman',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'azizansari',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backgrounds',
 'bad',
 'bag',
 'bail',
 'bailey',
 'bailing',
 'baker',
 'balance',
 'ballet',
 'band',
 'banished',
 'bank',
 'banker',
 'baptiste',
 'bar',
 'barbarahershey',
 'barbrastreisand',
 'barely',
 'bargained',
 'barney',
 'barriem',
 'barry',
 'barrylevinson',
 'barrypepper',
 'barryshabakahenley',
 'bars',
 'base',
 'baseball',
 'based',
 'basketball',
 'batman',
 'battle',
 'battles',
 'battling',
 'bay',
 'bdwong',
 'beach',
 'bear',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beaubridges',
 'beautiful',
 'beauty',
 'beccasweitzer',
 'bed',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'beloved',
 'ben',
 'benaffleck',
 'benchaplin',
 'benedictcumberbatch',
 'benfoster',
 'bengazzara',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'benmendelsohn',
 'bennett',
 'benstiller',
 'bent',
 'benwhishaw',
 'berger',
 'berlin',
 'bernardhill',
 'bernardlee',
 'berndeichinger',
 'berniemac',
 'best',
 'bet',
 'beth',
 'bethgrant',
 'betrayal',
 'bettemidler',
 'better',
 'betty',
 'beverly',
 'big',
 'bigger',
 'biggest',
 'biker',
 'billabbott',
 'billcamp',
 'billcobbs',
 'billduke',
 'billhader',
 'billionaire',
 'billmoseley',
 'billmurray',
 'billnighy',
 'billnunn',
 'billpankow',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billyburke',
 'billyconnolly',
 'billycrudup',
 'billycrystal',
 'billydeewilliams',
 'billyhopkins',
 'billyslaughter',
 'billywest',
 'billyzane',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bishop',
 'bit',
 'bitter',
 'bizarre',
 'black',
 'blade',
 'blake',
 'blakeclark',
 'blame',
 'blind',
 'block',
 'blonde',
 'blood',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'blythedanner',
 'board',
 'boarding',
 'boat',
 'bob',
 'bobbalaban',
 'bobbergen',
 'bobby',
 'bobbycannavale',
 'bobbymoynihan',
 'bobclendenin',
 'bobgunton',
 'bobhoskins',
 'bobpeterson',
 'bobstephenson',
 'bobweinstein',
 'body',
 'bokeemwoodbine',
 'bold',
 'bomb',
 'bond',
 'bonniehunt',
 'bonnietimmermann',
 'book',
 'books',
 'border',
 'bored',
 'boring',
 'born',
 'boss',
 'boston',
 'bound',
 'boundaries',
 'bounty',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boydbanks',
 'boydholbrook',
 'boyfriend',
 'boys',
 'braddourif',
 'bradgarrett',
 'bradleycooper',
 'bradleywhitford',
 'bradpitt',
 'bradwilliamhenke',
 'brain',
 'brave',
 'break',
 'breaking',
 'breaks',
 'breckinmeyer',
 'brendanfraser',
 'brendangleeson',
 'brendansextoniii',
 'brentbriscoe',
 'brentspiner',
 'brettcullen',
 'brettrice',
 'brian',
 'brianblessed',
 'briancox',
 'briandennehy',
 'briandepalma',
 'briandoyle',
 'briangrazer',
 'brianhowe',
 'brianj',
 'briano',
 'briansteele',
 'briantyler',
 'brianvanholt',
 'bride',
 'bridge',
 'bridgettewilson',
 'brief',
 'brielarson',
 'brien',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'brooklyn',
 'brooks',
 'brother',
 'brothers',
 'brought',
 'brown',
 'bruce',
 'bruceberman',
 'brucecampbell',
 'brucedern',
 'brucegreenwood',
 'brucemcgill',
 'brucespence',
 'brucewillis',
 'brutal',
 'brutally',
 'bryan',
 'bryancranston',
 'brycedallashoward',
 'bubasman',
 'buck',
 'buddies',
 'buddy',
 'budget',
 'build',
 'building',
 'built',
 'bully',
 'bumbling',
 'buried',
 'burns',
 'burtreynolds',
 'bus',
 'bush',
 'business',
 'businessman',
 'busy',
 'butler',
 'buy',
 'byrne',
 'cabin',
 'california',
 'called',
 'calls',
 'callumkeithrennie',
 'calvin',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'cameron',
 'cameronbright',
 'camerondiaz',
 'camgigandet',
 'camp',
 'campaign',
 'campbell',
 'campbellscott',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'capable',
 'capital',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraseymour',
 'card',
 'care',
 'career',
 'carefree',
 'careymulligan',
 'carl',
 'carlagallo',
 'carlagugino',
 'carlosalazraqui',
 'carlossaldanha',
 'carmen',
 'carmenelectra',
 'carolineaaron',
 'carolinegoodall',
 'carolkane',
 'carpenter',
 'carrie',
 'carriefisher',
 'carry',
 'carrying',
 'cars',
 'carter',
 'carterburwell',
 'cary',
 'caryelwes',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'catch',
 'catches',
 'cateblanchett',
 'catherinekeener',
 'catherineo',
 'catherinezeta',
 'cathey',
 'catholic',
 'cathysandrich',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cave',
 'cedrictheentertainer',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'celiaimrie',
 'celiaweston',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'certain',
 'chadmichaelmurray',
 'chain',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'chancekelly',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlesdance',
 'charlesdurning',
 'charlesmartinsmith',
 'charlesminsky',
 'charlesnapier',
 'charlesroven',
 'charless',
 'charlie',
 'charliekaufman',
 'charliesheen',
 'charlizetheron',
 'charlotterampling',
 'charltonheston',
 'charm',
 'charming',
 'chase',
 'chased',
 'chazzpalminteri',
 'cheating',
 'cheechmarin',
 'chef',
 'chelcieross',
 'chemical',
 'cher',
 'cherryjones',
 'chevychase',
 'chicago',
 'chief',
 'child',
 'childhood',
 'children',
 'chilling',
 'chimcbride',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloëgracemoretz',
 'chloësevigny',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chowyun',
 'chris',
 'chrisbauer',
 'chrisbender',
 'chriscooper',
 'chrisellis',
 'chrisevans',
 'chrishemsworth',
 'chriskattan',
 'chrisklein',
 'chrislebenzon',
 'chrismessina',
 'chrismiller',
 'chrismulkey',
 'chriso',
 'chrisparnell',
 'chrispenn',
 'chrispine',
 'chrispratt',
 'chrisrock',
 'christian',
 'christianbale',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christinebaranski',
 'christmas',
 'christopher',
 'christopherboyes',
 'christopherdoyle',
 'christophergreenbury',
 'christopherguest',
 'christopherlambert',
 'christopherlee',
 'christopherlloyd',
 'christophermcdonald',
 'christophermeloni',
 'christophermintz',
 'christophernolan',
 'christopherplummer',
 'christopherwalken',
 'christopheryoung',
 'christophwaltz',
 'chriswedge',
 'chrisweitz',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'ciaránhinds',
 'cillianmurphy',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'citizens',
 'city',
 'civil',
 'civilization',
 'claim',
 'claims',
 'claire',
 'clairedanes',
 'claireforlani',
 'clan',
 'clancybrown',
 'clark',
 'clarkduke',
 'clarkgregg',
 'clash',
 'class',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'claudevandamme',
 'cleaduvall',
 'clean',
 'clear',
 'clerk',
 'client',
 'cliffcurtis',
 'cliffmartinez',
 'cliftoncollinsjr',
 'clinteastwood',
 'clinthoward',
 'cliveowen',
 'clock',
 'clone',
 'clorisleachman',
 'close',
 'closer',
 'club',
 'clues',
 'clutches',
 'clydekusatsu',
 'coach',
 'coast',
 'cocaine',
 'code',
 'cody',
 'codycameron',
 'cohen',
 'col',
 'cold',
 'cole',
 'colehauser',
 'colinfarrell',
 'colinfirth',
 'colinhanks',
 'colinsalmon',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'colleenatwood',
 'colleencamp',
 'college',
 'collide',
 'collins',
 'collision',
 'colmfeore',
 'colmmeaney',
 'colonel',
 'colorful',
 'coma',
 'combat',
 'come',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comic',
 'comics',
 'coming',
 'command',
 'commander',
 'commit',
 'commitment',
 'committed',
 'common',
 'community',
 'companion',
 'company',
 'compete',
 'competing',
 'competition',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'compton',
 'computer',
 'concert',
 'conchataferrell',
 'condition',
 'confident',
 'conflict',
 'confront',
 'connected',
 'connection',
 'connell',
 'connienielsen',
 'connieray',
 'connor',
 'conquer',
 'conradvernon',
 'conscience',
 'consequences',
 'conspiracy',
 'constant',
 'constantly',
 'construction',
 'contact',
 'contest',
 'continue',
 'continues',
 'contract',
 'control',
 'controversial',
 'converge',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'core',
 'coreyburton',
 'coreyfeldman',
 'coreyjohnson',
 'coreystoll',
 'corner',
 'corporate',
 'corporation',
 'corrupt',
 'corruption',
 'cost',
 'costasmandylor',
 'couldn',
 'count',
 'country',
 'countryside',
 'couple',
 'couples',
 'courage',
 'courageous',
 'course',
 'court',
 'courteneycox',
 'courtneyb',
 'cousin',
 'cover',
 'covert',
 'cowboy',
 'crack',
 'craig',
 'craigbierko',
 'craigrobinson',
 'craigt',
 ...]

In [39]:
import nltk

In [40]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [41]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [42]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\susha\AppData\Local\Temp/ipykernel_6012/3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [43]:
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1930s',
 '1950s',
 '1960s',
 '1970s',
 '19th',
 '20',
 '200',
 '20th',
 '24',
 '25',
 '30',
 '40',
 '50',
 '60',
 '60s',
 'aaron',
 'aaroneckhart',
 'aarontaylor',
 'aaronyoo',
 'aasifmandvi',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abrahambenrubi',
 'abuse',
 'abusive',
 'academy',
 'accept',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'account',
 'accused',
 'ace',
 'achieve',
 'act',
 'action',
 'actions',
 'activities',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adambrody',
 'adamgoldberg',
 'adamlefevre',
 'adams',
 'adamsandler',
 'adamscott',
 'adaptation',
 'addiction',
 'adewaleakinnuoye',
 'adopted',
 'adrianmartinez',
 'adrianscarborough',
 'adrienbrody',
 'adult',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affections',
 'afghanistan',
 'africa',
 'african',
 'aftermath',
 'agbaje',
 'age',
 'aged',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aidanquinn',
 'aided',
 'ailing',
 'air',
 'airport',
 'aka',
 'al',
 'alanalda',
 'alanarkin',
 'alancumming',
 'alanrickman',
 'alansilvestri',
 'alantudyk',
 'alaska',
 'albert',
 'albertbrooks',
 'albertfinney',
 'albertr',
 'alcoholic',
 'alecbaldwin',
 'alecguinness',
 'alejandrogonzáleziñárritu',
 'alessandronivola',
 'alex',
 'alexandersiddig',
 'alexanderskarsgård',
 'alexandredesplat',
 'alexapenavega',
 'alexborstein',
 'alexisbledel',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'alfrewoodard',
 'ali',
 'alice',
 'alicedrummond',
 'aliciasilverstone',
 'aliciawitt',
 'alien',
 'aliens',
 'alike',
 'alilarter',
 'alive',
 'allancorduner',
 'allen',
 'allencovert',
 'alleong',
 'alliance',
 'allied',
 'allies',
 'allisonjanney',
 'allow',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alter',
 'alternate',
 'alternative',
 'alunarmstrong',
 'amanda',
 'amandamackey',
 'amandapeet',
 'amandaseyfried',
 'amazing',
 'amberheard',
 'ambervalletta',
 'ambition',
 'ambitious',
 'america',
 'americaferrera',
 'american',
 'americans',
 'amid',
 'amidst',
 'amp',
 'amy',
 'amyadams',
 'amypoehler',
 'amyryan',
 'amysedaris',
 'amysmart',
 'anagasteyer',
 'analyst',
 'ancient',
 'anderson',
 'andiemacdowell',
 'andreamartin',
 'andrebraugher',
 'andrew',
 'andrewdaly',
 'andrewstanton',
 'andy',
 'andydick',
 'andygarcía',
 'andyrichter',
 'andysamberg',
 'andyserkis',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angelo',
 'angry',
 'angusmacinnes',
 'animal',
 'animals',
 'animated',
 'animation',
 'anjelicahuston',
 'ann',
 'anna',
 'annafaris',
 'annakendrick',
 'annalevine',
 'annapaquin',
 'annapinnock',
 'annasophiarobb',
 'anndowd',
 'anne',
 'annebancroft',
 'annefletcher',
 'annehathaway',
 'anneheche',
 'annemccarthy',
 'annemoss',
 'annettebening',
 'annie',
 'annikapergament',
 'annual',
 'answer',
 'answers',
 'anthony',
 'anthonyanderson',
 'anthonybregman',
 'anthonyhopkins',
 'anthonymackie',
 'anti',
 'antics',
 'antonicorone',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartment',
 'apes',
 'apocalypse',
 'apocalyptic',
 'appear',
 'appears',
 'apple',
 'apprentice',
 'approaches',
 'april',
 'architect',
 'arcy',
 'area',
 'arielwinter',
 'arigraynor',
 'arise',
 'armed',
 'arminmueller',
 'arms',
 'armstrong',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arnonmilchan',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'arriving',
 'art',
 'arthur',
 'arthurj',
 'arthurtovey',
 'artist',
 'artists',
 'artlinson',
 'arts',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'aside',
 'ask',
 'asked',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassination',
 'assassins',
 'assigned',
 'assignment',
 'assistant',
 'assumes',
 'astronaut',
 'astronauts',
 'asylum',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attending',
 'attention',
 'attitude',
 'attorney',
 'attractive',
 'august',
 'aunjanueellis',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'avaacres',
 'avenge',
 'average',
 'avoid',
 'avykaufman',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'azizansari',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backgrounds',
 'bad',
 'bag',
 'bail',
 'bailey',
 'bailing',
 'baker',
 'balance',
 'ballet',
 'band',
 'banished',
 'bank',
 'banker',
 'baptiste',
 'bar',
 'barbarahershey',
 'barbrastreisand',
 'barely',
 'bargained',
 'barney',
 'barriem',
 'barry',
 'barrylevinson',
 'barrypepper',
 'barryshabakahenley',
 'bars',
 'base',
 'baseball',
 'based',
 'basketball',
 'batman',
 'battle',
 'battles',
 'battling',
 'bay',
 'bdwong',
 'beach',
 'bear',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beaubridges',
 'beautiful',
 'beauty',
 'beccasweitzer',
 'bed',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'beloved',
 'ben',
 'benaffleck',
 'benchaplin',
 'benedictcumberbatch',
 'benfoster',
 'bengazzara',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'benmendelsohn',
 'bennett',
 'benstiller',
 'bent',
 'benwhishaw',
 'berger',
 'berlin',
 'bernardhill',
 'bernardlee',
 'berndeichinger',
 'berniemac',
 'best',
 'bet',
 'beth',
 'bethgrant',
 'betrayal',
 'bettemidler',
 'better',
 'betty',
 'beverly',
 'big',
 'bigger',
 'biggest',
 'biker',
 'billabbott',
 'billcamp',
 'billcobbs',
 'billduke',
 'billhader',
 'billionaire',
 'billmoseley',
 'billmurray',
 'billnighy',
 'billnunn',
 'billpankow',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billyburke',
 'billyconnolly',
 'billycrudup',
 'billycrystal',
 'billydeewilliams',
 'billyhopkins',
 'billyslaughter',
 'billywest',
 'billyzane',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bishop',
 'bit',
 'bitter',
 'bizarre',
 'black',
 'blade',
 'blake',
 'blakeclark',
 'blame',
 'blind',
 'block',
 'blonde',
 'blood',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'blythedanner',
 'board',
 'boarding',
 'boat',
 'bob',
 'bobbalaban',
 'bobbergen',
 'bobby',
 'bobbycannavale',
 'bobbymoynihan',
 'bobclendenin',
 'bobgunton',
 'bobhoskins',
 'bobpeterson',
 'bobstephenson',
 'bobweinstein',
 'body',
 'bokeemwoodbine',
 'bold',
 'bomb',
 'bond',
 'bonniehunt',
 'bonnietimmermann',
 'book',
 'books',
 'border',
 'bored',
 'boring',
 'born',
 'boss',
 'boston',
 'bound',
 'boundaries',
 'bounty',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boydbanks',
 'boydholbrook',
 'boyfriend',
 'boys',
 'braddourif',
 'bradgarrett',
 'bradleycooper',
 'bradleywhitford',
 'bradpitt',
 'bradwilliamhenke',
 'brain',
 'brave',
 'break',
 'breaking',
 'breaks',
 'breckinmeyer',
 'brendanfraser',
 'brendangleeson',
 'brendansextoniii',
 'brentbriscoe',
 'brentspiner',
 'brettcullen',
 'brettrice',
 'brian',
 'brianblessed',
 'briancox',
 'briandennehy',
 'briandepalma',
 'briandoyle',
 'briangrazer',
 'brianhowe',
 'brianj',
 'briano',
 'briansteele',
 'briantyler',
 'brianvanholt',
 'bride',
 'bridge',
 'bridgettewilson',
 'brief',
 'brielarson',
 'brien',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'brooklyn',
 'brooks',
 'brother',
 'brothers',
 'brought',
 'brown',
 'bruce',
 'bruceberman',
 'brucecampbell',
 'brucedern',
 'brucegreenwood',
 'brucemcgill',
 'brucespence',
 'brucewillis',
 'brutal',
 'brutally',
 'bryan',
 'bryancranston',
 'brycedallashoward',
 'bubasman',
 'buck',
 'buddies',
 'buddy',
 'budget',
 'build',
 'building',
 'built',
 'bully',
 'bumbling',
 'buried',
 'burns',
 'burtreynolds',
 'bus',
 'bush',
 'business',
 'businessman',
 'busy',
 'butler',
 'buy',
 'byrne',
 'cabin',
 'california',
 'called',
 'calls',
 'callumkeithrennie',
 'calvin',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'cameron',
 'cameronbright',
 'camerondiaz',
 'camgigandet',
 'camp',
 'campaign',
 'campbell',
 'campbellscott',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'capable',
 'capital',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraseymour',
 'card',
 'care',
 'career',
 'carefree',
 'careymulligan',
 'carl',
 'carlagallo',
 'carlagugino',
 'carlosalazraqui',
 'carlossaldanha',
 'carmen',
 'carmenelectra',
 'carolineaaron',
 'carolinegoodall',
 'carolkane',
 'carpenter',
 'carrie',
 'carriefisher',
 'carry',
 'carrying',
 'cars',
 'carter',
 'carterburwell',
 'cary',
 'caryelwes',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'catch',
 'catches',
 'cateblanchett',
 'catherinekeener',
 'catherineo',
 'catherinezeta',
 'cathey',
 'catholic',
 'cathysandrich',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cave',
 'cedrictheentertainer',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'celiaimrie',
 'celiaweston',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'certain',
 'chadmichaelmurray',
 'chain',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'chancekelly',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlesdance',
 'charlesdurning',
 'charlesmartinsmith',
 'charlesminsky',
 'charlesnapier',
 'charlesroven',
 'charless',
 'charlie',
 'charliekaufman',
 'charliesheen',
 'charlizetheron',
 'charlotterampling',
 'charltonheston',
 'charm',
 'charming',
 'chase',
 'chased',
 'chazzpalminteri',
 'cheating',
 'cheechmarin',
 'chef',
 'chelcieross',
 'chemical',
 'cher',
 'cherryjones',
 'chevychase',
 'chicago',
 'chief',
 'child',
 'childhood',
 'children',
 'chilling',
 'chimcbride',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloëgracemoretz',
 'chloësevigny',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chowyun',
 'chris',
 'chrisbauer',
 'chrisbender',
 'chriscooper',
 'chrisellis',
 'chrisevans',
 'chrishemsworth',
 'chriskattan',
 'chrisklein',
 'chrislebenzon',
 'chrismessina',
 'chrismiller',
 'chrismulkey',
 'chriso',
 'chrisparnell',
 'chrispenn',
 'chrispine',
 'chrispratt',
 'chrisrock',
 'christian',
 'christianbale',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christinebaranski',
 'christmas',
 'christopher',
 'christopherboyes',
 'christopherdoyle',
 'christophergreenbury',
 'christopherguest',
 'christopherlambert',
 'christopherlee',
 'christopherlloyd',
 'christophermcdonald',
 'christophermeloni',
 'christophermintz',
 'christophernolan',
 'christopherplummer',
 'christopherwalken',
 'christopheryoung',
 'christophwaltz',
 'chriswedge',
 'chrisweitz',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'ciaránhinds',
 'cillianmurphy',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'citizens',
 'city',
 'civil',
 'civilization',
 'claim',
 'claims',
 'claire',
 'clairedanes',
 'claireforlani',
 'clan',
 'clancybrown',
 'clark',
 'clarkduke',
 'clarkgregg',
 'clash',
 'class',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'claudevandamme',
 'cleaduvall',
 'clean',
 'clear',
 'clerk',
 'client',
 'cliffcurtis',
 'cliffmartinez',
 'cliftoncollinsjr',
 'clinteastwood',
 'clinthoward',
 'cliveowen',
 'clock',
 'clone',
 'clorisleachman',
 'close',
 'closer',
 'club',
 'clues',
 'clutches',
 'clydekusatsu',
 'coach',
 'coast',
 'cocaine',
 'code',
 'cody',
 'codycameron',
 'cohen',
 'col',
 'cold',
 'cole',
 'colehauser',
 'colinfarrell',
 'colinfirth',
 'colinhanks',
 'colinsalmon',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'colleenatwood',
 'colleencamp',
 'college',
 'collide',
 'collins',
 'collision',
 'colmfeore',
 'colmmeaney',
 'colonel',
 'colorful',
 'coma',
 'combat',
 'come',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comic',
 'comics',
 'coming',
 'command',
 'commander',
 'commit',
 'commitment',
 'committed',
 'common',
 'community',
 'companion',
 'company',
 'compete',
 'competing',
 'competition',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'compton',
 'computer',
 'concert',
 'conchataferrell',
 'condition',
 'confident',
 'conflict',
 'confront',
 'connected',
 'connection',
 'connell',
 'connienielsen',
 'connieray',
 'connor',
 'conquer',
 'conradvernon',
 'conscience',
 'consequences',
 'conspiracy',
 'constant',
 'constantly',
 'construction',
 'contact',
 'contest',
 'continue',
 'continues',
 'contract',
 'control',
 'controversial',
 'converge',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'core',
 'coreyburton',
 'coreyfeldman',
 'coreyjohnson',
 'coreystoll',
 'corner',
 'corporate',
 'corporation',
 'corrupt',
 'corruption',
 'cost',
 'costasmandylor',
 'couldn',
 'count',
 'country',
 'countryside',
 'couple',
 'couples',
 'courage',
 'courageous',
 'course',
 'court',
 'courteneycox',
 'courtneyb',
 'cousin',
 'cover',
 'covert',
 'cowboy',
 'crack',
 'craig',
 'craigbierko',
 'craigrobinson',
 'craigt',
 ...]

In [44]:
from sklearn.metrics.pairwise import cosine_similarity

In [45]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [46]:
cosine_similarity(vectors)

array([[1.        , 0.09095086, 0.06063391, ..., 0.        , 0.        ,
        0.        ],
       [0.09095086, 1.        , 0.08823529, ..., 0.0285831 , 0.        ,
        0.        ],
       [0.06063391, 0.08823529, 1.        , ..., 0.0285831 , 0.        ,
        0.        ],
       ...,
       [0.        , 0.0285831 , 0.0285831 , ..., 1.        , 0.08333333,
        0.02946278],
       [0.        , 0.        , 0.        , ..., 0.08333333, 1.        ,
        0.05892557],
       [0.        , 0.        , 0.        , ..., 0.02946278, 0.05892557,
        1.        ]])

In [47]:
similarity = cosine_similarity(vectors)

In [48]:
similarity.shape

(4806, 4806)

In [49]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(4405, 0.2041241452319315),
 (539, 0.19050019050028574),
 (3608, 0.18870735310601722),
 (7, 0.18569533817705183),
 (972, 0.17928429140015903)]

In [50]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movie_list:
        print(new_df.iloc[i[0]].title)
    return

In [60]:
recommend('Mulan')

Legend of the Guardians: The Owls of Ga'Hoole
The Book of Life
The NeverEnding Story
Nicholas Nickleby
The Lost Medallion: The Adventures of Billy Stone

In [52]:
import pickle

In [61]:
pickle.dump(new_df.to_dict(),open('movies_dict.pkl','wb'))

In [62]:
pickle.dump(similarity,open('similarity.pkl','wb'))